# Generated by Django 2.0 on 2019-05-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyvalue',
            name='shebeiid',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
