# Generated by Django 2.0 on 2019-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20181224_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shebeiid',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
